export const CoreMetricsList = {
    status: 200,
    data: [
        {
            id: 0,
            metricsId: 1,
            name: 'End Date Variance',
            deliveryFunction: 'Work Plan Management',
            category: 'Schedule',
            formula: '((Baseline End Date (dd-mmm-yyyy) - Actual/Forecast End Date (dd-mmm-yyyy))/( Baseline End Date (dd-mmm-yyyy) - Baseline Start Date (dd-mmm-yyyy))) * 100',
            threshold1: '< -20,  > 20',
            threshold2: '>= -20, < -15, > 15, <=20',
            threshold3: '>= -15,  <= 15',
            unit: '%',
        },
        {
            id: 1,
            metricsId: 2,
            name: 'Cost Performance Index',
            deliveryFunction: 'Work Plan Management',
            category: 'Effort',
            formula: '(Earned Value (hrs)) / (Planned Value (hrs))',
            threshold1: '< 0.90',
            threshold2: '>= 0.90,  < 0.95, ',
            threshold3: '>= 0.95',
            unit: 'Number',
        },
        {
            id: 2,
            metricsId: 3,
            name: 'Schedule Performance Index',
            deliveryFunction: 'Work Plan Management',
            category: 'Schedule',
            formula: '(Earned Value (hrs)) / (Planned Value (hrs))',
            threshold1: '< 0.90',
            threshold2: '>= 0.90,  < 0.95, ',
            threshold3: '>= 0.95',
            unit: 'Number',
        },
        {
            id: 3,
            metricsId: 6,
            name: 'Overall Defect Rate',
            deliveryFunction: 'Defect Management',
            category: 'Quality',
            formula: '(No of Defects Pre-Release + No of Defects Post-Release)/ Actual Software Product Engineering (SPE) Effort',
            threshold1: '',
            threshold2: '',
            threshold3: '',
            unit: 'Number',
        },
        {
            id: 4,
            metricsId: 8,
            name: 'Total_Project_FTE',
            deliveryFunction: 'Resource Management',
            category: 'Resources',
            formula: 'Total_Project_FTE',
            threshold1: '',
            threshold2: '',
            threshold3: '',
            unit: 'Number',
        },
        {
            id: 5,
            metricsId: 9,
            name: 'Defect Density',
            deliveryFunction: 'Quality',
            category: 'Schedule',
            formula: 'Defect count/size of module or line of code',
            threshold1: '> 2',
            threshold2: 'Between 2-10',
            threshold3: '<= 1',
            unit: 'Number',
        },
        {
            id: 6,
            metricsId: 10,
            name: 'Defect Rejection Ratio',
            deliveryFunction: 'Quality',
            category: 'Quality',
            formula: 'No Of defects rejected/total number of defects',
            threshold1: '>2',
            threshold2: 'Between 1 - 2',
            threshold3: '> 0-1',
            unit: '',
        },
        {
            id: 7,
            metricsId: 11,
            name: 'Defect Leakage Ratio',
            deliveryFunction: 'Quality',
            category: 'Quality',
            formula: 'No of defect found in UAT/No Of defects found in QA Testing',
            threshold1: '>2',
            threshold2: 'Between 1 - 2',
            threshold3: '> 0-1',
            unit: '',
        },
        {
            id: 8,
            metricsId: 13,
            name: 'Cost of Rework - ATD',
            deliveryFunction: 'Work Plan Management',
            category: 'Quality',
            formula: '( Total Actual Rework effort / Actuals To Date (ATD)) * 100',
            threshold1: '>15',
            threshold2: '> 10,  <= 15',
            threshold3: '<= 10',
            unit: '%',
        },
        {
            id: 9,
            metricsId: 14,
            name: 'Variance At Completion',
            deliveryFunction: 'Work Plan Management',
            category: 'Effort',
            formula: 'Budget At Completion -(Project Estimated to Complete+Actuals To Date (ATD))',
            threshold1: '',
            threshold2: '',
            threshold3: '',
            unit: 'Hours',
        },
        
       

    ]

}